version: '3'

services:
  # Service MySQL
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password  # Remplacez par votre mot de passe
      MYSQL_DATABASE: my_database    # Nom de votre base de données
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Service pour l'application web
  web:
    build: ./web
    ports:
      - "8080:80"  # Port externe:interne
    volumes:
      - ./web/src:/var/www/html

  # Service pour l'API
  api:
    build: ./api
    ports:
      - "3001:80"  # Port externe:interne
    volumes:
      - ./api/src:/var/www/html
    depends_on:
      - mysql

  # phpMyAdmin pour la gestion de la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password  # Utilisez le même mot de passe que pour MySQL
      PMA_DATABASE: ressourcerie # Nom de votre base de données
    depends_on:
      - mysql

volumes:
  mysql_data:
